name: hexyll-pandoc
version: 0.1.0.0
github: "Hexirp/hexirp-hakyll"
license: GPL-3.0-or-later
author: "Hexirp"
maintainer: "https://github.com/Hexirp/yhseq"
copyright: "(c) 2019 Hexirp"

synopsis: A implementation of hexyll's compiler by pandoc
category: Web

description: Please see the README on GitHub at <https://github.com/Hexirp/hexirp-hakyll#readme>

extra-source-files:
- README.md
- ChangeLog.md
- test/data/embed.html
- test/data/example.md
- test/data/example.md.metadata
- test/data/images/favicon.ico
- test/data/just-meta.html
- test/data/just-meta.html.out
- test/data/partial-helper.html
- test/data/partial.html
- test/data/partial.html.out
- test/data/posts/2010-08-26-birthday.md
- test/data/posts/2018-09-26.md
- test/data/posts/2019/05/10/tomorrow.md
- test/data/russian.md
- test/data/strip.html
- test/data/strip.html.out
- test/data/template.html
- test/data/template.html.out
- data/templates/atom-item.xml
- data/templates/atom.xml
- data/templates/rss-item.xml
- data/templates/rss.xml

dependencies:
- base                 >= 4.11.1.0 && < 4.13
- binary               >= 0.8.5.1  && < 0.9
- filepath             >= 1.4.2    && < 1.5
- text                 >= 1.2.3.1  && < 1.3
- unordered-containers >= 0.2.9.0  && < 0.3
- vector               >= 0.12.0.2 && < 0.13
- yaml                 >= 0.8.32   && < 0.12
- pandoc               >= 2.2.1    && < 2.6
- pandoc-citeproc      >= 0.14.8.1 && < 0.16
- hexyll-core          == 0.1.0.*

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  other-modules:
  - Hexyll.Web.Pandoc.Binary

tests:
  hexyll-pandoc-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hexyll-pandoc
    - containers       >= 0.5.11.0 && < 0.7
    - QuickCheck       >= 2.11.3   && < 2.13
    - tasty            >= 1.1.0.4  && < 1.3
    - tasty-hunit      >= 0.10.0.1 && < 0.11
    - tasty-quickcheck >= 0.10     && < 0.11
