resolver: lts-13.30

flags:
  hexirp-hakyll:
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
- 'hexirp-hakyll-core'
- 'hexirp-hakyll'

nix:
  enable: false
  packages:
  - zlib
