resolver: lts-13.30

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
- '.'

nix:
  enable: false
  packages:
  - zlib
