resolver: lts-13.29
save-hackage-creds: false

flags:
  hexirp-hakyll:
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- 'cmark-gfm-0.2.0'
- 'hslua-module-system-0.2.1'
- 'ipynb-0.1'
- 'lrucache-1.2.0.1'
- 'pandoc-2.7.3'
- 'pandoc-citeproc-0.16.2'
- 'skylighting-0.8.2'
- 'skylighting-core-0.8.2'
